# Global application values.  These are used to display the app name, send emails, and ::Settingsure where system emails go.
application_name: 'CMAT'             # Common name for your application.  i.e. My App, Billy Bob, etc

from_email:       'support@opentapestry.com'  # Emails will come from this address i.e. noreply@example.com, support@example.com, system@example.com, etc
from_email_name:  'Open Tapestry'             # This will show up as the name on emails.  i.e. support@example.com <Example>
support_email:    'support@opentapestry.com'  # Support email for your application.  This is used for contact us etc.
admin_email:      'admin@opentapestry.com'    # Admin email for your application
comments_email:   'commments@opentapestry.com'  # Emails that contain notifications of comments.

email_server_address: "example.com"
email_user_name: 'cmat'    # Email server username
email_password: 'examplepassword'              # Email server password

assertion_consumer_service_url: 'https://cmat.herokuapp.com/saml/consume'
issuer: 'https://cmat.herokuapp.com'
idp_sso_target_url: 'https://idp.mit.edu/idp/Authn/MIT'
idp_cert_fingerprint: ''
name_identifier_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'
entity_id: "https://cmat.herokuapp.com/saml"
tech_contact_name: "Administrator"
tech_contact_email: "admin@opentapestry.com"
saml_private_key: "keys/cmat.herokuapp.com.saml.key"
saml_certificate: "keys/cmat.herokuapp.com.saml.crt"

test:
  email_server_address: "example.com"
  email_user_name: 'cmat'    # Email server username
  email_password: 'examplepassword'              # Email server password

production:
  email_server_address: "smtp.sendgrid.net"
  email_user_name: 'cmat'    # Email server username
  email_password: 'eS9X22UVSWDf'              # Email server password
  assertion_consumer_service_url: 'https://cmat.herokuapp.com/saml/consume'
  issuer: 'https://cmat.herokuapp.com/saml'
  idp_sso_target_url: 'https://idp.mit.edu/idp/Authn/MIT'
  idp_cert_fingerprint: ''
  name_identifier_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'
  entity_id: "https://cmat.herokuapp.com/saml"
  tech_contact_name: "Administrator"
  tech_contact_email: "admin@opentapestry.com"
  saml_private_key: "keys/cmat.herokuapp.com.saml.key"
  saml_certificate: "keys/cmat.herokuapp.com.saml.crt"

